#!/bin/bash

# $1 : input file

tmp=$(mktemp)
trap "rm $tmp" EXIT

echo "inlining all included files"
echo "Be sure each \\input command is in the beginning of line and is not followed by any texts."
echo "Check it below:"
echo "================================"
grep "\\\\input" *.tex
echo "================================"


while ( grep '^ *\\input{[^}]*} *$' $1 ); do
    echo "found an input line"
    awk -f $(dirname $0)/inline-tex-sub.awk $1 > $tmp
    cp $tmp $1
done


echo "inlining bibitems"
BIBFILE=`echo $1 | sed 's/.tex/.bbl/'`
awk -v filename=$BIBFILE '{ if ($0 ~ ".bibliography{") { system("cat "filename); } else { print $0; } }' < $1 > $tmp
cp $tmp $1


