
name       = default
latexmk    = perl latexmk/latexmk.pl
sources    = $(wildcard *.tex) $(wildcard *.sty) $(wildcard *.bib)
max_pages  = 8

.PHONY: all imgs clean allclean auto \
	submission archive arxiv clean-submission

all: abstract.txt $(name).pdf standalone-supplement.pdf

abstract.txt: abstract.tex scripts/remove-comment.awk
	( echo "% this file is autogenerated from abstract.tex " ; \
	  echo "% copy-past from this file to web-based paper submission systems " ; \
	  echo "% that requires a plain text abstract." ; \
	  echo "% " ; \
	  awk -f scripts/remove-comment.awk $< ) > $@


$(name).tex: Makefile
	( echo "% This file is autogenerated. See Makefile and README " ; echo "\input{main.tex}") > $@
	grep -q $(name).tex .gitignore || (echo $(name).tex >> .gitignore)

%.aux %.bbl %.blg %.fls %.log %.out %.fdb_latexmk %.pdf: %.tex imgs $(sources)
	-$(latexmk) -pdf \
		   -latexoption="-halt-on-error -shell-escape" \
		   -bibtex \
		   $<

%.ja.aux %.ja.bbl %.ja.blg %.ja.fls %.ja.log %.ja.out %.ja.fdb_latexmk %.ja.pdf: %.tex imgs $(sources)
	$(latexmk) -r latexmk/rc_ja.pl \
		   -latexoption="-halt-on-error -shell-escape" \
		   -pdfdvi \
		   -bibtex \
		   $<

auto:
	+bash scripts/make-periodically.sh

imgs:
	$(MAKE) -C img

clean: clean-submission
	-rm -r *~ *.aux *.dvi *.log *.toc *.bbl *.*pyg* *.out \
		*.blg *.utf8 *.elc $(name).pdf supplemental.pdf combined.pdf \
		*.fdb_latexmk __* *.fls *.subm* \
		_minted*

allclean: clean
	$(MAKE) -C img clean

include scripts/submission.mk
